name: RisingLavaChallenge
version: '1.0.1'
main: org.doughston.risingLavaChallenge.RisingLavaChallenge
api-version: '1.21'
authors: [ doughston ]
commands:
  startlava:
    description: Starts the lava rising challenge
    usage: /startlava <timeInSeconds> <worldSizeX> <worldSizeZ> <startDelayInSeconds> [startLayer]
  stoplava:
    description: Stops the lava rising challenge
    usage: /stoplava
  setborder:
    description: Sets the world border
    usage: /setborder <worldSizeX> <worldSizeZ>
  pauselava:
    description: Pauses the lava rising challenge
    usage: /pauselava
  resumelava:
    description: Resumes the lava rising challenge
    usage: /resumelava
  help:
    description: Displays help information
    usage: /help