name: RisingLavaChallenge
version: '1.0.1'
main: org.doughston.risingLavaChallenge.RisingLavaChallenge
api-version: '1.21'
authors: [ doughston ]
commands:
  startlava:
    description: Starts the lava rising challenge
    usage: /startlava
  stoplava:
    description: Stops the lava rising challenge
    usage: /stoplava
  setborder:
    description: Sets the world border
    usage: /setborder <worldSizeX> <worldSizeZ>